"use client"
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Registry from '@src/registry'

import ViewBox from 'naxui/ViewBox'
import Container from 'naxui/Container'

import { useMediaScreen } from 'naxui-manager'

import Header from '@src/components/Header'
import Stack from 'naxui/Stack'


// export const metadata: Metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {

	const sereen = useMediaScreen()

	return (
		<html lang="en">
			<body>
				<Registry>
					<Container maxWidth="sm" >
						<ViewBox
							header={sereen.isUp('sm') ? <Header /> : <></>}
							// header={window.innerWidth >= 599 ? <Header /> : <></>}
							footer={sereen.isDown('sm') ? <Header /> : <></>}
							height="100vh"
							direction='column'
							flexWrap="wrap"
						>
							<Stack
								flex={1}
								bgcolor="color.paper"
								borderRadius={2}
								mt={sereen.isDown('sm') ? 2 : 0}
								mb={sereen.isUp('sm') ? 2 : 0}
								p={1}
								justifyContent="space-between"
							>

								{children}
							</Stack>
						</ViewBox>
					</Container>
				</Registry>
			</body>
		</html>
	)
}
